default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sattam_essentials_development
  username: postgres
  password: password
  host: localhost
  port: 5432

production:
  <<: *default
  url: <%= ENV['PRODUCTION_DATABASE_URL'] %>
