default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sattam_essentials_development
  username: postgres
  password: iamA@lekh23
  host: localhost
  port: 5432

# test:
#   <<: *default
#   database: sattam_essentials_test

production:
  <<: *default
  database: sattam_essentials_production
  username: sattam_essentials
  password: <%= ENV["SATTAM_ESSENTIALS_DATABASE_PASSWORD"] %>
